### ISSUE TITLE
munging human-intended qvm-ls output

### ISSUE THREAD

**Issue by jpouellet** [mig5/qubes-scripts#1]
Instead of trying to chop off or interpret the []{}=> symbols around vm names (which are intended for humans) you can use qvm-ls's --raw-data option to get parsing-friendly output. For example, to get the names of all templates, you could do:
```
list_templates() {
    qvm-ls --raw-data name-raw type \
    | while IFS='|' read name type; do
        [ Tpl = "$type" ] && echo "$name"
    done | sort
}
```

Using `name-raw` instead of the human-intended `name` is preferable because `name` has additional symbols which you don't currently handle, and `name-raw` avoids the need to handle any altogether.

in qvm-ls, name is constructed like this:
```
    "name": {"func": "('=>' if qvm_collection.get_default_template() is not None\
             and vm.qid == qvm_collection.get_default_template().qid else '')\
             + ('[' if vm.is_template() else '')\
             + ('<' if vm.is_disposablevm() else '')\
             + ('{' if vm.is_netvm() else '')\
             + vm.name \
             + (']' if vm.is_template() else '')\
             + ('>' if vm.is_disposablevm() else '')\
             + ('}' if vm.is_netvm() else '')"},
```

Note that `<` `>` are also valid, and not handled by your:
[`TEMPLATES=$(qvm-ls --raw-data name | grep "\\[" | tr -d {}[]=\> | sort)`](https://github.com/mig5/qubes-scripts/blob/master/qubes-template-update#L8)

In your current code, <> could be left in and passed as name arguments, and in your case due to lack of quoting potentially lead to unintended io redirection to files named by running DisposableVMs.

**Comment by mig5** [comment]
Wow, somehow I never saw this - thanks for the tip, folded that in to the template update script.
